### ISSUE TITLE
Incorrect y_min and y_max acceptance criteria for MixtureDensityEstimator.pdf

### ISSUE THREAD

**Issue by AhmedThahir** [koaning/scikit-mdn#1]
**Problem**

The current implementation in line 175-176 will break if `y_min = 0` or `y_max = 0` supplied by the programmer, since `if 0` will always evaluate to `if False`.

https://github.com/koaning/scikit-mdn/blob/e471b056439c17d179ed11522c4a26d9b33f4ed2/skmdn/__init__.py#L175-L176

**Solution**

Will create a PR to address this as instructed by probabl's YouTube admin.

**Comment by koaning** [comment]
Closing due to merger.
